spring:
  #config server configuration
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
  #Database configuration
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: ${DB_NAME}


server:
  port: ${SERVER.PORT}




